
#=========== FOR LOCAL DEVELOPMENT ========


# services:
#   
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/app
#     command: uvicorn server:app --host 0.0.0.0 --port 8000

#   frontend:
#    build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "4242:4242"
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#       - /app/node_modules
#     command: npm run dev



#=========== FOR REMOTE SERVER ========
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    env_file:
      - .env
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      

