
#=========== FOR LOCAL DEVELOPMENT ========


# services:
#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/app
#     command: uvicorn server:app --host 0.0.0.0 --port 8000

#   backend:
#     build:
#       context: ./backend
#       dockerfile: Dockerfile
#     ports:
#       - "8000:8000"
#     volumes:
#       - ./backend:/app
#     command: uvicorn server:app --host 0.0.0.0 --port 8000

#   frontend:
#    build:
#       context: ./frontend
#       dockerfile: Dockerfile
#     ports:
#       - "4242:4242"
#     volumes:
#       - ./frontend:/app
#       - /app/node_modules
#       - /app/node_modules
#     command: npm run dev



#=========== FOR REMOTE SERVER ========

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - VITE_BACKEND_URL=http://198.71.51.17/api 
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - VITE_BACKEND_URL=http://198.71.51.17/api 
    command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "8000"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4242:4242"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_BACKEND_URL=http://198.71.51.17/api
    command: ["serve", "-s", "dist", "-l", "4242"]